<?php



	$helper = Mage::helper('yieldify_helper');


	$yieldify_uuid = $helper->getVariable();
	$environment = $helper->getDomain();
?>
<?php if(!is_null($yieldify_uuid) && $yieldify_uuid!=='') { ?>
<script>
	(function(d) {
		var e = d.createElement('script');
		e.src = d.location.protocol + '//<?php echo $environment; ?>/yieldify/code.js?w_uuid=<?php echo $yieldify_uuid; ?>&loca=' + window.location.href;
		e.async = true;
		d.getElementsByTagName('head')[0].appendChild(e);
	}(document));
</script>
<?php } ?>
