<?php

	$helper = Mage::helper('yieldify_helper');
	$yieldify_uuid = $helper->getVariable();
	$yieldify_regex = $helper->getIDRegex();

	$yieldify_error = Mage::registry('yieldify_error');
	$yieldify_error_status = null;
	switch ($yieldify_error) {
		case 'none':
			$yieldify_error = 'The Yieldify ID is valid and was successfully updated.';
			$yieldify_error_status = 'success';
			break;
		case 'clear':
			$yieldify_last_valid_id = Mage::registry('yieldify_last_valid_id');
			$id_string = (is_null($yieldify_last_valid_id)||$yieldify_last_valid_id==='') ? '' : " ($yieldify_last_valid_id)";
			$yieldify_error = 'Your Yieldify ID'.$id_string.' was successfully cleared';
			$yieldify_error_status = 'success';
			break;
		case 'format':
			$yieldify_error = 'The ID you provided is not a valid Yieldify ID. A valid ID is made up of letters and numbers and looks like this: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx';
			$yieldify_error_status = 'error';
			break;
		case 'server':
			$yieldify_error = 'There was a problem connecting to Yieldify, please try again or contact Yieldify if the issue persists.';
			$yieldify_error_status = 'error';
			break;
		case 'invalid':
			$yieldify_error = 'The Yieldify ID you entered does not exist, please double check the value you entered or contact Yieldify to make sure you have the correct ID.';
			$yieldify_error_status = 'error';
			break;
		case 'unknown':
			$yieldify_error = 'An unknown error has occured, please contact Yieldify to make sure you have the correct ID.';
			$yieldify_error_status = 'error';
			break;
		default:
			$yieldify_error = null;
			$yieldify_error_status = null;
			break;
	}

	$yieldify_index_url = Mage::helper('adminhtml')->getUrl('adminhtml/yieldifyuuid/index');
	$yieldify_clear_url = Mage::helper('adminhtml')->getUrl('adminhtml/yieldifyuuid/clear');
?>
<script>
	function _yieldify_redirect_set_uuid(action) {
		document.getElementById('_yieldify_uuid_submit').disabled = true;
		document.getElementById('_yieldify_uuid_clear').disabled = true;
		var element_value = document.getElementById('_yieldify_uuid_input').value;
		if(action==='clear') {
			var confirmation = confirm('Are you sure you want to clear your Yieldify ID?');
			if(confirmation) {
				window.location = '<?php echo $yieldify_clear_url; ?>';
			}
			else {
				document.getElementById('_yieldify_uuid_submit').disabled = false;
				document.getElementById('_yieldify_uuid_clear').disabled = false;
			}
		}
		else if(action==='index') {
			window.location = '<?php echo $yieldify_index_url; ?>' + 'new_uuid/' + element_value;
		}
		else {
			window.location = '<?php echo $yieldify_index_url; ?>';
		}
	}
</script>

<?php if(!is_null($yieldify_error_status)) { ?>
<div id="messages"><ul class="messages"><li class="<?php echo $yieldify_error_status; ?>-msg"><ul><li><span>
	<?php echo $yieldify_error; ?>
</span></li></ul></li></ul></div>
<?php } ?>

<div class="content-header"><table cellspacing="0"><tbody><tr><td>
	<h3>Yieldify</h3>
	<p class="form-buttons">
		<button id="_yieldify_uuid_clear" title="Clear" type="button" class="scalable" onclick="javascript:_yieldify_redirect_set_uuid('clear');" style="">
			<span><span><span>Clear Yieldify ID</span></span></span>
		</button>
		<button id="_yieldify_uuid_submit" title="Save" type="button" class="scalable save" onclick="javascript:_yieldify_redirect_set_uuid('index');" style="">
			<span><span><span>Validate &amp; Save</span></span></span>
		</button>
	</p>
</td></tr></tbody></table></div>
<div class="content-body">
	<label>Please insert the unique Yieldify ID you were provided during account set-up:</label>
	<input id="_yieldify_uuid_input" type="text" value="<?php echo $yieldify_uuid; ?>" style="width: 250px;" />
</div>
