<?php

	$helper = Mage::helper('yieldify_helper');
	$yieldify_uuid = $helper->getVariable();
?>
<div class="content-header"><table cellspacing="0"><tbody><tr><td>
	<h3>Yieldify</h3>
</td></tr></tbody></table></div>

<script>
	function _yieldify_redirect_set_uuid() {
		document.getElementById('_yieldify_uuid_submit').disabled = true;
		document.getElementById('_yieldify_uuid_submit').value = 'Saving';
		var element_value = document.getElementById('_yieldify_uuid_input').value;
		var url_str = window.location.href;
		if(url_str.slice(-1)!=='/') {
			url_str += '/';
		}
		var url_arr = url_str.split('/');
		var i = 0;
		for(i=0; i<url_arr.length; i++) {
			if(url_arr[i]==='yieldifyuuid')
				break;
		}
		if(url_arr[i+1]!=='index') {
			url_arr.splice(i+1, 0, 'index');
		}
		window.location = url_arr.join('/') + 'new_uuid/' + element_value;
	}
</script>
<div class="content-body">
	<label>Please insert the unique Yieldify ID you were provided during account set-up:</label>
	<input id="_yieldify_uuid_input" type="text" value="<?php echo $yieldify_uuid; ?>" style="width: 250px;"/>
	<input id="_yieldify_uuid_submit" type="submit" value="Save" onclick="javascript:_yieldify_redirect_set_uuid();" style="width: 60px;"></input>
</div>
